### ISSUE TITLE
PragmataPro running in Terminal.app with "antialias text" on a non-retina display cause it to render illegible

### ISSUE THREAD

**Issue by kevinsjoberg** [fabrizioschiavi/pragmatapro#186] opened 2020-09-30 06:16 UTC
On a Retina display PragmataPro renders fine in Terminal.app, but on a non-retina display it's completely illegible when "antialias text" is unchecked. See the screenshot below.

![Screenshot 2020-09-30 at 08 16 29](https://user-images.githubusercontent.com/503025/94649582-3f77f000-02f5-11eb-9a8d-7b3ac0cb3152.png)

**Env**

**Operating System:** macOS Catalina (`10.15.6`)
**Terminal:** Terminal.app (`Version 2.10 (433)`)
**Monitor:** BenQ PD2500Q

**Comment by fabrizioschiavi** [comment] 2020-09-30 06:43
Very strange… The screenshot comes from an Apple Retina Display?

**Comment by jspiro** [comment] 2020-09-30 06:47
I've seen major Pragmata issues in iTerm in Big Sur, but I don't think it's related to Pragmata itself but ligatures.

Which OS ?

**Comment by KevinSjoberg** [comment] 2020-09-30 06:50
@jspiro my bad for not providing that upfront.

I'm running macOS Catalina (10.15.6) using Terminal.app (Version 2.10 (433)). I've updated the original issue with this information as well.

**Comment by jspiro** [comment] 2020-09-30 06:51
Just for comparison, can you try iTerm?

**Comment by KevinSjoberg** [comment] 2020-09-30 06:55
@jspiro I don't see the problem in iTerm. I also don't experience this problem in Terminal.app when I'm at home, using my LG Ultrafine 5K display.

**Comment by fabrizioschiavi** [comment] 2020-09-30 08:08
I can reproduce it 😲 Also PragmataPro without ligatures doesn't work properly.
Thanks for letting me know Kevin, I must find a solution as soon as possible but I have no idea where is the problem at the moment.

**Comment by jspiro** [comment] 2020-09-30 08:22
Honestly, if you have a connection with them, you might want to reach out to the iTerm folks. They're very familiar with the rendering differences, and they have their own Pragmata issues, so the might be able to help (admittedly I never had issues in Catalina in iTerm, but ligatures are extremely broken in iTerm in Big Sur–which I've reported already).

**Comment by fabrizioschiavi** [comment] 2020-09-30 08:33
Thanks for the suggestion @jspiro !
@gnachman could you help me to understand what changed in iTerm?

**Comment by KevinSjoberg** [comment] 2020-09-30 08:44
@jspiro @fabrizioschiavi thanks for the fast response. Keep in mind that the behaviour I'm seeing is in Terminal.app, not iTerm. Just want to make sure we're all on the same page.

**Comment by gnachman** [comment] 2020-10-01 05:42
PragmataPro has had idiopathic problems when non-antialiased for a some time. I expect this is a duplicate of #129.

**Comment by fabrizioschiavi** [comment] 2021-04-14 17:40
Duplicate of #129

**Closed by fabrizioschiavi** 2021-04-14 17:40 UTC
